name: Wriststone CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: 'ubuntu-22.04'

    steps:
      - name: Setup .NET
        with:
          dotnet-version: '10.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish API
        run: dotnet publish Wriststone.Wriststone/Wriststone.Wriststone.API/Wriststone.Wriststone.API.csproj --configuration Release --output ./publish --no-build

      - name: Upload published files
        with:
          name: wriststone-app
          path: ./publish
